on:
  workflow_dispatch:
    inputs: 
      wingetid:
        description: 'source package name in winget'
        required: true
        type: string
      chocoid:
        description: 'destination package name in chocolatey'
        required: true
        type: string
      admin:
        required: true
        type: boolean

jobs:
  convert-winget-package-to-chocolatey:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64

    steps:
    - uses: actions/checkout@v1
    
    - name: install python dependencies
      run: pip install -r requirements.txt

    - name: download winget package repo
      run: git clone https://github.com/microsoft/winget-pkgs --depth 1

    - name: convert (non-admin)
      if: ${{ !inputs.admin }}
      run: python wg2choco.py ${{ inputs.wingetid }} ${{ inputs.chocoid }}
    
    - name: convert (admin)
      if: ${{ inputs.admin }}
      run: python wg2choco.py ${{ inputs.wingetid }} ${{ inputs.chocoid }} --admin
    
    - name: zip compress
      run: 7z a ${{ inputs.chocoid }}.zip ./${{ inputs.chocoid }}/*

    - name: choco pack
      run: choco pack ${{ inputs.chocoid }}/${{ inputs.chocoid }}.nuspec
    
    - name: Download PaExec
      run: |
        choco install wget --no-progress 
        wget -q https://www.poweradmin.com/paexec/paexec.exe -P C:\Windows\System32
    
    - name: Create new user
      run: net user foo p@ssw0rd /add
    
    - name: test choco package install (non-admin)
      if: ${{ !inputs.admin }}
      run: |
        paexec -u foo -p p@ssw0rd -lo $pwd\output.txt -w $pwd cinst ${{ inputs.chocoid }}.${{ env.version }}.nupkg 
        cat output.txt
    
    - name: test choco package uninstall (non-admin)
      if: ${{ !inputs.admin }}
      run: |
        paexec -u foo -p p@ssw0rd -lo $pwd\output.txt -w $pwd cuninst ${{ inputs.chocoid }}
        cat output.txt

    - name: test choco package install (admin)
      #if: ${{ inputs.admin }}
      run: cinst ${{ inputs.chocoid }}.${{ env.version }}.nupkg
    
    - name: test choco package uninstall (admin)
      #if: ${{ inputs.admin }}
      run: cuninst ${{ inputs.chocoid }}

    - name: upload artifact chocolatey nuget package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ inputs.chocoid }}.${{ env.version }}.nupkg
        path: ${{ inputs.chocoid }}.${{ env.version }}.nupkg
    
    - name: upload artifact chocolatey raw package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ inputs.chocoid }}.zip
        path: ${{ inputs.chocoid }}.zip
