on:
  workflow_dispatch:
    inputs: 
      wingetid:
        description: 'source package name in winget'
        required: true
        type: string
      chocoid:
        description: 'destination package name in chocolatey'
        required: true
        type: string

jobs:
  convert-winget-package-to-chocolatey:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
          
    steps:
    - uses: actions/checkout@v1
    
    - name: install python dependencies
      run: pip install -r requirements.txt

    - name: download winget package repo
      run: git clone https://github.com/microsoft/winget-pkgs --depth 1

    - name: convert winget package to chocolatey package with wg2choco.py
      run: python wg2choco.py ${{ inputs.wingetid }} ${{ inputs.chocoid }}
    
    - name: zip compress
      run: 7z a ${{ inputs.chocoid }}.zip ./${{ inputs.chocoid }}/*

    - name: choco pack
      run: choco pack ${{ inputs.chocoid }}/${{ inputs.chocoid }}.nuspec
    
    - name: test choco package install
      run: cinst ${{ inputs.chocoid }}.${{ env.version }}.nupkg
    
    - name: test choco package uninstall
      run: cuninst ${{ inputs.chocoid }}
    
    - name: upload artifact chocolatey nuget package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ inputs.chocoid }}.${{ env.version }}.nupkg
        path: ${{ inputs.chocoid }}.${{ env.version }}.nupkg
    
    - name: upload artifact chocolatey raw package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ inputs.chocoid }}.zip
        path: ${{ inputs.chocoid }}.zip